[build-system]
requires = ["hatchling"]
build-backend = "main.build"
[project]
name = "example_package_Andraziel"
version = "0.0.1"
authors = [
  { name="Auxence", email="auxence.deleuziere@isen.yncrea.fr" },
]
description = "test package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]